name: make python devex basics

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install dependencies
      env:
        # Force overwriting during tests since a human cannot intervene
        BREW_BUNDLE_OPTS: --force
      run: make deps

    - name: Run check
      run: make check

    - name: Run tests
      run: make test

    - name: Run build
      run: make build
