name: make python devex basics

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-13
          - macos-14
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Add Poetry install location to PATH in shell rcfiles
      run: |
        echo 'export PATH="${HOME}/.local/bin:$PATH"' | tee -a ~/.zshrc | tee -a ~/.bashrc

    - name: Install dependencies
      env:
        # Force overwriting during tests since a human cannot intervene
        # Do not upgrade dependents unless we have to
        BREW_BUNDLE_OPTS: --force --no-upgrade
      run: make deps

    - name: Run check
      run: make check

    - name: Run tests
      run: make test

    - name: Run build
      run: make build
