# from https://github.com/browniebroke/pre-commit-autoupdate-action
name: Pre-commit auto-update
on:
  # every day at midnight
  schedule:
    - cron: "0 16 * * 3"
  # on demand  
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
      
      - uses: browniebroke/pre-commit-autoupdate-action@main
      
      - uses: peter-evans/create-pull-request@v6
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          delete-branch: true
          labels: dependencies
          title: "Update pre-commit hooks"
          commit-message: "chore: update pre-commit hooks"
          body: Update versions of pre-commit hooks to the latest version.
          add-paths: ".pre-commit-config.yaml"
